language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - "pypy"
install:
  #- "pip install pep8 --use-mirrors"
  - "python setup.py install"
before_script:
  #- "pep8"
  - pip install sympy --use-mirrors
script:
  - "python mathics/test.py"
after_script:
  - "python mathics/benchmark.py"
notifications:
  email: false
